### PR TITLE
Reverting temporary shuttering changes and MA changes

### PR DESCRIPTION
**Pull request by chandraAndem**

### CODE REVIEW

**Comment by chandraAndem** [comment]
test this please

**Comment by chandraAndem** [comment]
test this please

**Comment by chandraAndem** [comment]
test this please

**Comment by chandraAndem** [comment]
test this please

**Comment by chandraAndem** [comment]
test this please

**Comment by chandraAndem** [comment]
test this please

**Comment by chandraAndem** [comment]
test this please

**Review by ashwinirudrappa — DISMISSED** [review]

**Review by sauravkitukale — DISMISSED** [review]

**Comment by chandraAndem** [comment]
test this please

**Review by ashwinirudrappa — APPROVED** [review]

**Pull request merged**
